# Enable C++ support
language: cpp

# Establish which builds we wish to test
matrix:
    include:
	- os: linux
	  compiler: gcc
	- os: linux
	  compiler: clang
	- os: osx
	  compiler: gcc
	- os: osx
	  compiler: clang

#os:
#  - linux
#  - osx

# Compiler selection
#compiler:
#  - gcc
#  - clang

# Allow compiling with c++11
dist: trusty

# Build steps
script:
  - mkdir build
  - cd build
  - cmake ..
  - make