# Enable C++ support
language: cpp

git:
  depth: false
  
addons:
  sonarcloud:
    organization: "jvinniec-github"
    token:
      secure: $SONAR_TOKEN

# block the following branches from triggering builds
branches:
  except:
  - gh-pages

# Establish which builds we wish to test
matrix:
    include:
        # Test Linux with GCC
        - os: linux
          compiler: gcc

        # Test Linux with Clang
        - os: linux
          compiler: clang

        # Test OSX with GCC
        - os: osx
          compiler: gcc

        # Test OSX with previous Clang
        - os: osx
          compiler: clang
          osx_image: xcode9.4

        # Test OSX with Clang (latest version)
        - os: osx
          compiler: clang
          osx_image: xcode10.1


# Allow compiling with c++11
dist: xenial

# Build steps
script:
  - cmake -Dcoverage=1 ./
  - make
  - make test

after_success:
  # Only run sonar-scanner if we're using a linux machine with clang
  # This prevents generating a code coverage/status reports for each
  # build configuration
  - bash gen_coverage.sh

# TODO: also need to test pure autotools build
