# Enable C++ support
language: cpp

addons:
  sonarcloud:
    organization: "jvinniec-github"
    token:
      secure: $SONAR_TOKEN
    branches:
      - master
      - travis_buldtest

# block the following branches from triggering builds
branches:
  except:
  - gh-pages

# Establish which builds we wish to test
matrix:
    include:
        # Test Linux with GCC
        - os: linux
          compiler: gcc

        # Test Linux with Clang
        - os: linux
          compiler: clang

        # Test OSX with GCC
        - os: osx
          compiler: gcc

        # Test OSX with previous Clang
        - os: osx
          compiler: clang
          osx_image: xcode8.3

        # Test OSX with Clang (latest version)
        - os: osx
          compiler: clang
          osx_image: xcode9.2


# Allow compiling with c++11
dist: trusty

# Build steps
script:
  - cmake ./
  - make
  - make test

after_success:
 - sonar-scanner

# TODO: also need to test pure autotools build